{
  "training_args.output_dir": "models/bert-base-uncased-transileration-en-ar-v4",
  "training_args.learning_rate": 2e-5,
  "training_args.per_device_train_batch_size": 4,
  "training_args.num_train_epochs": 10,
  "training_args.metric_for_best_model": "error_rate",
  "training_args.greater_is_better": False,
  "early_stopping.early_stopping_patience": 3,
}