{
  "training_args.n_epochs": 15,
  "training_args.batch_size": 32,
  "training_args.hidden_size": 128,
  "training_args.learning_rate": 0.003,
  "training_args.l2": 1.5e-4,
  "training_args.teacher_forcing_value": 0.5,
  "training_args.teacher_forcing_type": 'fixed',
  "training_args.dropout": 0.15,
  "training_args.reverse_in": False,
  "training_args.bidirectional_encoder": True,
  "training_args.decoder_attention": True,
}